### ISSUE TITLE
does not work with webdriver 4.0

### ISSUE THREAD

**Issue by parisholley** [webdriverio/wdio-sync#26] opened 2016-01-29 17:31 UTC
see webdriverio/webdriverio#1063 for some background. it appears this line:

```
runInFiberContext(
                INTERFACES[this.config.mochaOpts.ui][2],
                this.config.beforeHook,
                this.config.afterHook,
                fnName
            )
```
is preventing tests promise chaining from working correctly

**Comment by christian-bromann** [comment] 2016-02-04 16:15
can you provide a reproducible example?

**Comment by christian-bromann** [comment] 2016-03-17 16:13
I was not able to reproduce this issue. Closing

**Closed by christian-bromann** 2016-03-17 16:13 UTC
